### ISSUE TITLE
Product Category [Tablet]: Sub-category menu functionality needs to change

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#104]
At 768 view
Sample: http://dev.culligandiy.com/Undersink-Systems

The stacking of the sub-categories isn't working here, especially when there is a longer list. 
Recommend implementing what @nickpaventi did on Insight.com project using the '+' expanding menu. 

- [x] Add expandable menu used on Insight.com ('+')
- [x] Label should read 'Choose a system' or 'Choose a filter type' depending on the category
- [x] Clicking expands the sub-menu, pushing the page content down
- [x] Click maintains anchor functionality it has now

![screenshot 2015-04-09 15 39 53](https://cloud.githubusercontent.com/assets/10550484/7078512/b01250ea-dece-11e4-9a90-52ed48cc6414.png)

**Comment by seanriceaz** [comment]
added this at 12510
```css
.nav-toggle-container a{
  line-height:1.6;
  background-color: #67666B;
  color: #FFF;
  font-size: 20px;
  padding: 14px 35px;
  display: block;
  border-bottom: 1px solid #8E8E8E;
  margin-left: 0px;
}

.nav-toggle-container a span{
    margin-top:7px;
}
.page-content .site-navigation{
  overflow:hidden;
  max-height:0;
  -webkit-transition:max-height .2s ease-in-out;
  transition:max-height .2s ease-in-out;
}
.page-content .site-navigation.open{
  max-height:1000px;
}

```

added this at 12529

```css
  /* Hide the nav toggler on larger screens */
  .nav-toggle-container{
    display:none;
  }
  .page-content .site-navigation{
      max-height:none;
  }
```

Javascript incoming
