### ISSUE TITLE
Product Category [Mobile]: Feature #1 and 2 need style updates

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#105]
**Feature 1**
- [x] Add consistent padding to left and right of feature content, currently touches left edge
- [x] Add padding between product name and 'perfect solution...' title

**Feature 2**
- [x] Image and content should flow like Feature 1
- [x] Colors may need to change for tags, content and CTA to work in this new flow
- [x] Should not be a border on the blue CTA

Let's discuss real time if needed...

![features-mobile](https://cloud.githubusercontent.com/assets/10550484/7078666/285134e4-ded0-11e4-9eb3-64a5fecc0a27.png)

**Comment by seanriceaz** [comment]
Added `medium-collapse` to the row instead of `collapse`.

Had to add this to line 6310 of the css
```css
  .row.medium-collapse > .column,
  .row.medium-collapse > .columns {
    position: relative;
    padding-left: 0;
    padding-right: 0;
    float: left;
  }
  .row .row.medium-collapse {
    width: auto;
    margin: 0;
    max-width: none;
    *zoom: 1;
  }
  .row .row.medium-collapse:before, .row .row.medium-collapse:after {
    content: " ";
    display: table;
  }

  .row .row.medium-collapse:after {
    clear: both;
  }
```
