### ISSUE TITLE
Product Detail [Mobile]: Overview tab 

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#110]
The perfect solution and tabs should be included in the Overview tab (when it's closed these items should be hidden as well)

![content-in-tab](https://cloud.githubusercontent.com/assets/10550484/7079922/75db460a-dedf-11e4-82ee-402283b7b146.png)

**Comment by seanriceaz** [comment]
Fixed.

CSS line 12848
```css
.product-detail-content .accordion-container .section-custom-accordion.overview {
  padding:0 10px;
}
```

Also added a clearfix to the css ( like 30 or so) and had to rearrange the code slightly.

**Comment by seanriceaz** [comment]
clearfix code is here:
```css
.clearfix *{
  zoom:1;
}
.clearfix:before, .clearfix:after { content: " "; display: table; }
.clearfix:after { clear: both; }
```

**Comment by seanriceaz** [comment]
Had to add another fix to the css
Line 13112
```css
/* line 184, /Users/nickpaventi/Sites/culligan-diy/_build/_scss/custom/product_detail.scss */
  .product-detail-content .accordion-container .section-custom-accordion section.active,
  .product-detail-content .accordion-container .section-custom-accordion .product-detail-main
  {
    margin-bottom: 100px;
  }
```
